name: build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Setup Python
      run: uv python install
    - name: Build package
      run: uv build
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
          name: clinlp-build
          path: dist
  make-requirements:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Setup Python
      run: uv python install
    - name: Download build
      uses: actions/download-artifact@v5
      with:
        name: clinlp-build
        path: dist
    - name: Create requirements file for test environment
      run: |
        uv export -o requirements.txt --only-group dev --no-hashes 
        find dist/*.whl | xargs -I {} echo {}"[transformers, metrics, apps]" >> requirements.txt
    - name: Upload requirements file
      uses: actions/upload-artifact@v4
      with:
          name: clinlp-requirements        
          path: requirements.txt
  test-build:
    needs: make-requirements
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v5
        with:
          name: clinlp-build
          path: dist
      - name: Download requirements file
        uses: actions/download-artifact@v5
        with:
          name: clinlp-requirements
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install requirements using pip
        run: pip install -r requirements.txt
      - name: Test build
        run: poe test 
  publish:
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup Python
        run: uv python install
      - name: Download build
        uses: actions/download-artifact@v5
        with:
          name: clinlp-build
          path: dist
      - name: Publish package
        run: uv publish --token ${{ SECRETS.PYPI_TOKEN }}
