name: format-lint

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  check-formatting-linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Setup Python
      run: uv python install      
    - name: Install dependencies
      run: uv sync --only-dev
    - name: ruff
      run: uv run poe check