name: format-lint

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:

  check-formatting-linting:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Install dependencies
      run: uv sync --only-dev

    - name: ruff
      run: uv run ruff check